man_stand: 'human'
man_lay: 'human'
person_walking: 'human'
house: 'house'
house_3: 'house'
ice: 'rock'
oak_tree: 'tree'
pine_tree: 'tree'
pine_tree_broken: 'broken_tree'
butte: 'butte'
stone: 'rock'
stone_large: 'rock'
lamp_post: 'lamp_post'
jersey_barrier : 'barrier'
