
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AIM_CAMERA CAMERA CONTINUE DEPTH FNUM GET INUM MOVE OBJECTS PATROL POS ROTATE STOP TO UINUM VELOCITYcmd : STOPcmd : CONTINUEcmd : VELOCITY fval fvalcmd : MOVE fvalcmd : ROTATE fvalcmd : TO fval fval fvalcmd : AIM_CAMERA fval fvalcmd : GET POScmd : GET CAMERA UINUMcmd : GET DEPTH UINUMcmd : GET OBJECTScmd : PATROLfval : FNUMfval : INUMfval : UINUM'
    
_lr_action_items = {'STOP':([0,],[2,]),'CONTINUE':([0,],[3,]),'VELOCITY':([0,],[4,]),'MOVE':([0,],[5,]),'ROTATE':([0,],[6,]),'TO':([0,],[7,]),'AIM_CAMERA':([0,],[8,]),'GET':([0,],[9,]),'PATROL':([0,],[10,]),'$end':([1,2,3,10,12,13,14,15,16,19,22,23,25,26,27,28,],[0,-1,-2,-12,-13,-14,-15,-4,-5,-8,-11,-3,-7,-9,-10,-6,]),'FNUM':([4,5,6,7,8,11,12,13,14,17,18,24,],[12,12,12,12,12,12,-13,-14,-15,12,12,12,]),'INUM':([4,5,6,7,8,11,12,13,14,17,18,24,],[13,13,13,13,13,13,-13,-14,-15,13,13,13,]),'UINUM':([4,5,6,7,8,11,12,13,14,17,18,20,21,24,],[14,14,14,14,14,14,-13,-14,-15,14,14,26,27,14,]),'POS':([9,],[19,]),'CAMERA':([9,],[20,]),'DEPTH':([9,],[21,]),'OBJECTS':([9,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cmd':([0,],[1,]),'fval':([4,5,6,7,8,11,17,18,24,],[11,15,16,17,18,23,24,25,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cmd","S'",1,None,None,None),
  ('cmd -> STOP','cmd',1,'p_cmd_1','parser.py',43),
  ('cmd -> CONTINUE','cmd',1,'p_cmd_2','parser.py',47),
  ('cmd -> VELOCITY fval fval','cmd',3,'p_cmd_3','parser.py',51),
  ('cmd -> MOVE fval','cmd',2,'p_cmd_4','parser.py',55),
  ('cmd -> ROTATE fval','cmd',2,'p_cmd_5','parser.py',59),
  ('cmd -> TO fval fval fval','cmd',4,'p_cmd_6','parser.py',63),
  ('cmd -> AIM_CAMERA fval fval','cmd',3,'p_cmd_7','parser.py',67),
  ('cmd -> GET POS','cmd',2,'p_cmd_8','parser.py',71),
  ('cmd -> GET CAMERA UINUM','cmd',3,'p_cmd_9','parser.py',75),
  ('cmd -> GET DEPTH UINUM','cmd',3,'p_cmd_10','parser.py',79),
  ('cmd -> GET OBJECTS','cmd',2,'p_cmd_11','parser.py',83),
  ('cmd -> PATROL','cmd',1,'p_cmd_12','parser.py',87),
  ('fval -> FNUM','fval',1,'p_fval_1','parser.py',91),
  ('fval -> INUM','fval',1,'p_fval_2','parser.py',95),
  ('fval -> UINUM','fval',1,'p_fval_3','parser.py',99),
]
