  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  lwheel_state_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwheel_j
    pid: {p: 30.0, i: 0.1, d: 0.1, i_clamp: 100}

  rwheel_state_controller:
    type: velocity_controllers/JointVelocityController
    joint: rwheel_j
    pid: {p: 30.0, i: 0.1, d: 0.1, i_clamp: 100}

  lwheel2_state_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwheel2_j
    pid: {p: 30.0, i: 0.1, d: 0.1, i_clamp: 100}

  rwheel2_state_controller:
    type: velocity_controllers/JointVelocityController
    joint: rwheel2_j
    pid: {p: 30.0, i: 0.1, d: 0.1, i_clamp: 100}

  mobile_base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: [lwheel_j]
    right_wheel: [rwheel_j]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    wheel_separation: 1.
    wheel_radius: 0.3

    base_frame_id: target_robot/base_link

    enable_odom_tf: false
    publish_cmd: True
    allow_multiple_cmd_vel_publishers: True

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.
        min_velocity: -1.

        has_acceleration_limits: true
        max_acceleration: 2.
        min_acceleration: -2.

        has_jerk_limits: false
        # max_jerk: 5.
      angular:
        z:
          has_velocity_limits: true
          max_velocity: 1.

          has_acceleration_limits: true
          max_acceleration: 2.5

          has_jerk_limits: false
          # max_jerk: 2.5
